apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-docker-image-from-git-source
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: tag
        description: Docker tag to use for preview images
        default: latest
      - name: pathToDockerFile
        description: The path to the dockerfile to build
        default: /workspace/source/Dockerfile
      - name: base
        default: /workspace/source
      - name: pathToContext
        description:
          The build context used by Kaniko
          (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
        default:  /workspace/source
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: jx-creds
      image: jenkinsxio/jx:1.3.906
      command:
        - jx
        - step
        - git
        - credentials
      workingDir: "/workspace/source"
      resources:
        limits:
          cpu: 0.2
          memory: 256Mi
        requests:
          cpu: 0.1
          memory: 128Mi
    - name: integration-test
      image: jenkinsxio/builder-go:5a997a5f9dbfb42d5aece0d688537f7f
      command:
        - make
        - test-slow-integration
      workingDir: "/workspace/source"
      env:
        - name: GOPATH
          value: /workspace/go
        - name: GIT_COMMITTER_EMAIL
          value: jenkins-x@googlegroups.com
        - name: GIT_AUTHOR_EMAIL
          value: jenkins-x@googlegroups.com
        - name: GIT_AUTHOR_NAME
          value: jenkins-x-bot
        - name: GIT_COMMITTER_NAME
          value: jenkins-x-bot
        - name: BRANCH_NAME
          value: PR-248
        - name: PULL_NUMBER
          value: "248"
        - name: BUILD_ID
          value: "1"
        # - name: GOPROXY
        #   value: http://jx-app-athens-athens-proxy
        - name: GOPROXY
          value: http://athens-proxy.jx.cd.jenkins-x.io
      resources:
        limits:
          cpu: 3
          memory: 5120Mi
        requests:
          cpu: 2
          memory: 4096Mi
    - name: build-binary
      image: docker.io/golang:1.11.5
      command:
        - make
        - linux
      workingDir: "/workspace/source"
      env:
        - name: GOPATH
          value: /workspace/go
        # - name: GOPROXY
        #   value: http://jx-app-athens-athens-proxy
      resources:
        limits:
          cpu: 2
          memory: 4096Mi
        requests:
          cpu: 1
          memory: 2018Mi
    - name: ls
      image: docker.io/golang:1.11.5
      command:
        - ls
        - -al
      workingDir: "/workspace/source/build"
      env:
        - name: GOPATH
          value: /workspace/go
    - name: validate-binary
      image: docker.io/golang:1.11.5
      command:
        - ./build/linux/jx
        - --help
      workingDir: "/workspace/source"
      env:
        - name: GOPATH
          value: /workspace/go
    - name: build-and-push-image
      image: rawlingsj/executor:dev17
      command:
        - /kaniko/executor
      args:
        - --dockerfile=${inputs.params.pathToDockerFile}
        - --destination=docker.io/jenkinsxio/jx:0.0.0-${inputs.params.tag}
        - --context=${inputs.params.pathToContext}
        - --cache-repo=jenkins-x-docker-registry.jx.svc.cluster.local:5000/
        - --cache=true
        - --cache-dir=/workspace
        - --skip-tls-verify-registry=jenkins-x-docker-registry.jx.svc.cluster.local:5000
    - name: build-and-push-nodejs
      image: rawlingsj/executor:dev17
      command:
        - /kaniko/executor
      args:
        - --dockerfile=${inputs.params.base}/Dockerfile.builder-nodejs
        - --destination=docker.io/jenkinsxio/builder-maven:SNAPSHOT-JX-${inputs.params.tag}
        - --context=${inputs.params.pathToContext}
        - --cache-repo=jenkins-x-docker-registry.jx.svc.cluster.local:5000/
        - --cache=true
        - --cache-dir=/workspace
        - --skip-tls-verify-registry=jenkins-x-docker-registry.jx.svc.cluster.local:5000
    - name: build-and-push-maven
      image: rawlingsj/executor:dev17
      command:
        - /kaniko/executor
      args:
        - --dockerfile=${inputs.params.base}/Dockerfile.builder-maven
        - --destination=docker.io/jenkinsxio/builder-maven:SNAPSHOT-JX-${inputs.params.tag}
        - --context=${inputs.params.pathToContext}
        - --cache-repo=jenkins-x-docker-registry.jx.svc.cluster.local:5000/
        - --cache=true
        - --cache-dir=/workspace
        - --skip-tls-verify-registry=jenkins-x-docker-registry.jx.svc.cluster.local:5000
    - name: build-and-push-go
      image: rawlingsj/executor:dev17
      command:
        - /kaniko/executor
      args:
        - --dockerfile=${inputs.params.base}/Dockerfile.builder-go
        - --destination=docker.io/jenkinsxio/builder-maven:SNAPSHOT-JX-${inputs.params.tag}
        - --context=${inputs.params.pathToContext}
        - --cache-repo=jenkins-x-docker-registry.jx.svc.cluster.local:5000/
        - --cache=true
        - --cache-dir=/workspace
        - --skip-tls-verify-registry=jenkins-x-docker-registry.jx.svc.cluster.local:5000
    - name: preview
      image: jenkinsxio/builder-go:5a997a5f9dbfb42d5aece0d688537f7f
      command:
        - ./jx/scripts/ci.sh
      workingDir: "/workspace/source"
      env:
        - name: PREVIEW_IMAGE_TAG
          value: SNAPSHOT-JX-${inputs.params.tag}
        - name: HOME
          value: /workspace
        - name: GOPATH
          value: /workspace/go
        - name: GIT_COMMITTER_EMAIL
          value: jenkins-x@googlegroups.com
        - name: GIT_AUTHOR_EMAIL
          value: jenkins-x@googlegroups.com
        - name: GIT_AUTHOR_NAME
          value: jenkins-x-bot
        - name: GIT_COMMITTER_NAME
          value: jenkins-x-bot
        - name: BRANCH_NAME
          value: PR-248
        - name: PULL_NUMBER
          value: "248"
        - name: BUILD_ID
          value: "1"
        # - name: GOPROXY
        #   value: http://jx-app-athens-athens-proxy
        - name: GOPROXY
          value: http://athens-proxy.jx.cd.jenkins-x.io
      resources:
        limits:
          cpu: 3
          memory: 5120Mi
        requests:
          cpu: 2
          memory: 4096Mi